/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicStartRouteImport } from './routes/_public/start'
import { Route as AdminEventsSlugRouteImport } from './routes/admin_.events.$slug'
import { Route as AdminFormsFormIdRouteImport } from './routes/admin_.forms.$formId'
import { Route as PublicCfpEventSlugFormSlugRouteImport } from './routes/_public/cfp.$eventSlug.$formSlug'
import { Route as AdminEventsSlugSubmissionsRouteImport } from './routes/admin_.events.$slug_.submissions'
import { Route as AdminEventsSlugTaxonomiesRouteImport } from './routes/admin_.events.$slug_.taxonomies'
import { Route as AdminEventsSlugSubmissionsSubmissionIdRouteImport } from './routes/admin_.events.$slug_.submissions_.$submissionId'
import { Route as AdminFormsFormIdVersionsVersionIdRouteImport } from './routes/admin_.forms.$formId_.versions.$versionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicStartRoute = PublicStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => PublicRoute,
} as any)
const AdminEventsSlugRoute = AdminEventsSlugRouteImport.update({
  id: '/admin_/events/$slug',
  path: '/admin/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormsFormIdRoute = AdminFormsFormIdRouteImport.update({
  id: '/admin_/forms/$formId',
  path: '/admin/forms/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicCfpEventSlugFormSlugRoute =
  PublicCfpEventSlugFormSlugRouteImport.update({
    id: '/cfp/$eventSlug/$formSlug',
    path: '/cfp/$eventSlug/$formSlug',
    getParentRoute: () => PublicRoute,
  } as any)
const AdminEventsSlugSubmissionsRoute =
  AdminEventsSlugSubmissionsRouteImport.update({
    id: '/admin_/events/$slug_/submissions',
    path: '/admin/events/$slug/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsSlugTaxonomiesRoute =
  AdminEventsSlugTaxonomiesRouteImport.update({
    id: '/admin_/events/$slug_/taxonomies',
    path: '/admin/events/$slug/taxonomies',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsSlugSubmissionsSubmissionIdRoute =
  AdminEventsSlugSubmissionsSubmissionIdRouteImport.update({
    id: '/admin_/events/$slug_/submissions_/$submissionId',
    path: '/admin/events/$slug/submissions/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminFormsFormIdVersionsVersionIdRoute =
  AdminFormsFormIdVersionsVersionIdRouteImport.update({
    id: '/admin_/forms/$formId_/versions/$versionId',
    path: '/admin/forms/$formId/versions/$versionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/start': typeof PublicStartRoute
  '/admin/events/$slug': typeof AdminEventsSlugRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRoute
  '/cfp/$eventSlug/$formSlug': typeof PublicCfpEventSlugFormSlugRoute
  '/admin/events/$slug/submissions': typeof AdminEventsSlugSubmissionsRoute
  '/admin/events/$slug/taxonomies': typeof AdminEventsSlugTaxonomiesRoute
  '/admin/events/$slug/submissions/$submissionId': typeof AdminEventsSlugSubmissionsSubmissionIdRoute
  '/admin/forms/$formId/versions/$versionId': typeof AdminFormsFormIdVersionsVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/start': typeof PublicStartRoute
  '/admin/events/$slug': typeof AdminEventsSlugRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRoute
  '/cfp/$eventSlug/$formSlug': typeof PublicCfpEventSlugFormSlugRoute
  '/admin/events/$slug/submissions': typeof AdminEventsSlugSubmissionsRoute
  '/admin/events/$slug/taxonomies': typeof AdminEventsSlugTaxonomiesRoute
  '/admin/events/$slug/submissions/$submissionId': typeof AdminEventsSlugSubmissionsSubmissionIdRoute
  '/admin/forms/$formId/versions/$versionId': typeof AdminFormsFormIdVersionsVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRoute
  '/_public/start': typeof PublicStartRoute
  '/admin_/events/$slug': typeof AdminEventsSlugRoute
  '/admin_/forms/$formId': typeof AdminFormsFormIdRoute
  '/_public/cfp/$eventSlug/$formSlug': typeof PublicCfpEventSlugFormSlugRoute
  '/admin_/events/$slug_/submissions': typeof AdminEventsSlugSubmissionsRoute
  '/admin_/events/$slug_/taxonomies': typeof AdminEventsSlugTaxonomiesRoute
  '/admin_/events/$slug_/submissions_/$submissionId': typeof AdminEventsSlugSubmissionsSubmissionIdRoute
  '/admin_/forms/$formId_/versions/$versionId': typeof AdminFormsFormIdVersionsVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/start'
    | '/admin/events/$slug'
    | '/admin/forms/$formId'
    | '/cfp/$eventSlug/$formSlug'
    | '/admin/events/$slug/submissions'
    | '/admin/events/$slug/taxonomies'
    | '/admin/events/$slug/submissions/$submissionId'
    | '/admin/forms/$formId/versions/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/start'
    | '/admin/events/$slug'
    | '/admin/forms/$formId'
    | '/cfp/$eventSlug/$formSlug'
    | '/admin/events/$slug/submissions'
    | '/admin/events/$slug/taxonomies'
    | '/admin/events/$slug/submissions/$submissionId'
    | '/admin/forms/$formId/versions/$versionId'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/admin'
    | '/_public/start'
    | '/admin_/events/$slug'
    | '/admin_/forms/$formId'
    | '/_public/cfp/$eventSlug/$formSlug'
    | '/admin_/events/$slug_/submissions'
    | '/admin_/events/$slug_/taxonomies'
    | '/admin_/events/$slug_/submissions_/$submissionId'
    | '/admin_/forms/$formId_/versions/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRoute
  AdminEventsSlugRoute: typeof AdminEventsSlugRoute
  AdminFormsFormIdRoute: typeof AdminFormsFormIdRoute
  AdminEventsSlugSubmissionsRoute: typeof AdminEventsSlugSubmissionsRoute
  AdminEventsSlugTaxonomiesRoute: typeof AdminEventsSlugTaxonomiesRoute
  AdminEventsSlugSubmissionsSubmissionIdRoute: typeof AdminEventsSlugSubmissionsSubmissionIdRoute
  AdminFormsFormIdVersionsVersionIdRoute: typeof AdminFormsFormIdVersionsVersionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/start': {
      id: '/_public/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof PublicStartRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin_/events/$slug': {
      id: '/admin_/events/$slug'
      path: '/admin/events/$slug'
      fullPath: '/admin/events/$slug'
      preLoaderRoute: typeof AdminEventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/forms/$formId': {
      id: '/admin_/forms/$formId'
      path: '/admin/forms/$formId'
      fullPath: '/admin/forms/$formId'
      preLoaderRoute: typeof AdminFormsFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/cfp/$eventSlug/$formSlug': {
      id: '/_public/cfp/$eventSlug/$formSlug'
      path: '/cfp/$eventSlug/$formSlug'
      fullPath: '/cfp/$eventSlug/$formSlug'
      preLoaderRoute: typeof PublicCfpEventSlugFormSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin_/events/$slug_/submissions': {
      id: '/admin_/events/$slug_/submissions'
      path: '/admin/events/$slug/submissions'
      fullPath: '/admin/events/$slug/submissions'
      preLoaderRoute: typeof AdminEventsSlugSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/events/$slug_/taxonomies': {
      id: '/admin_/events/$slug_/taxonomies'
      path: '/admin/events/$slug/taxonomies'
      fullPath: '/admin/events/$slug/taxonomies'
      preLoaderRoute: typeof AdminEventsSlugTaxonomiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/events/$slug_/submissions_/$submissionId': {
      id: '/admin_/events/$slug_/submissions_/$submissionId'
      path: '/admin/events/$slug/submissions/$submissionId'
      fullPath: '/admin/events/$slug/submissions/$submissionId'
      preLoaderRoute: typeof AdminEventsSlugSubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/forms/$formId_/versions/$versionId': {
      id: '/admin_/forms/$formId_/versions/$versionId'
      path: '/admin/forms/$formId/versions/$versionId'
      fullPath: '/admin/forms/$formId/versions/$versionId'
      preLoaderRoute: typeof AdminFormsFormIdVersionsVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicStartRoute: typeof PublicStartRoute
  PublicCfpEventSlugFormSlugRoute: typeof PublicCfpEventSlugFormSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicStartRoute: PublicStartRoute,
  PublicCfpEventSlugFormSlugRoute: PublicCfpEventSlugFormSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRoute,
  AdminEventsSlugRoute: AdminEventsSlugRoute,
  AdminFormsFormIdRoute: AdminFormsFormIdRoute,
  AdminEventsSlugSubmissionsRoute: AdminEventsSlugSubmissionsRoute,
  AdminEventsSlugTaxonomiesRoute: AdminEventsSlugTaxonomiesRoute,
  AdminEventsSlugSubmissionsSubmissionIdRoute:
    AdminEventsSlugSubmissionsSubmissionIdRoute,
  AdminFormsFormIdVersionsVersionIdRoute:
    AdminFormsFormIdVersionsVersionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
