import { DEFAULT_EVENT_SLUG, DEFAULT_FORM_SLUG } from '../../lib/default-event'

export type TourChapterId =
  'orientation' | 'organizer' | 'submitter' | 'speaker' | 'reviewer' | 'programme'

export const TOUR_CHAPTERS: readonly { readonly id: TourChapterId; readonly label: string }[] = [
  { id: 'orientation', label: 'Orientation' },
  { id: 'organizer', label: 'Organizer workspace' },
  { id: 'submitter', label: 'Submitter access' },
  { id: 'speaker', label: 'Speaker portal' },
  { id: 'reviewer', label: 'Reviewer workspace' },
  { id: 'programme', label: 'Public programme' },
]

export interface TourStep {
  readonly id: string
  readonly chapter: TourChapterId
  readonly title: string
  readonly body: string
  readonly route?: string
  readonly params?: Readonly<Record<string, string>>
  readonly access: 'organizer' | 'public' | 'portal' | 'evaluation'
  readonly target?: string
  readonly mobileTarget: string | null
  readonly targetPolicy: 'required' | 'optional' | 'none'
  readonly mode: 'observe' | 'guided'
  readonly placement: 'auto' | 'center'
  readonly fixtureAssertions: readonly string[]
  readonly maxTransitionMs: number
  readonly requiresSession?: 'organizer'
}

const eventParams = { slug: DEFAULT_EVENT_SLUG } as const
const showcaseFormId = 'f0000000-0000-4000-8000-000000000001'
const showcaseSubmissionId = 'd0000000-0000-4000-8000-000000000807'
const moment = (value: TourStep): TourStep => value

export const TOUR_ORGANIZER_HOLD = {
  title: 'Organizer access needs attention',
  body: 'This sandbox role could not open. Retry it, return to the sign-in door, or continue with the public chapters.',
} as const

export const TOUR_STEPS: readonly TourStep[] = [
  moment({
    id: 'welcome',
    chapter: 'orientation',
    title: 'From proposal to programme',
    body: 'Orby is your Open Events assistant. If you need help anywhere in this tour, open Ask Orby and ask a question. Then follow one DemoConf proposal through intake, review, speaker work, scheduling, and the public programme. Temporary demo access is read-only.',
    access: 'public',
    target: 'orby-launcher',
    mobileTarget: 'orby-launcher',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['Orby assistant launcher', 'DemoConf event identity'],
    maxTransitionMs: 3000,
  }),
  moment({
    id: 'admin-signin',
    chapter: 'orientation',
    title: 'Organizer sign-in',
    body: 'This is the normal organizer door. The next chapter opens a separate read-only sandbox role without exposing or replacing a real login.',
    route: '/admin',
    access: 'public',
    target: 'admin-signin',
    mobileTarget: 'admin-signin',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['Organizer access door'],
    maxTransitionMs: 5000,
  }),
  moment({
    id: 'event-settings',
    chapter: 'organizer',
    title: 'Event overview',
    body: 'The event pulse links settings, CFP state, submissions, speaker readiness, and the agenda. Dates and public identity stay editable below.',
    route: '/admin/events/$slug',
    params: eventParams,
    access: 'organizer',
    target: 'event-overview',
    mobileTarget: 'event-overview',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['Published event pulse', 'CFP state'],
    maxTransitionMs: 6000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'events',
    chapter: 'organizer',
    title: 'Event workspace',
    body: 'The event list keeps DemoConf distinct from every other workspace and makes the active conference easy to reopen.',
    route: '/admin/events',
    access: 'organizer',
    target: 'events-list',
    mobileTarget: 'events-list',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['DemoConf event row'],
    maxTransitionMs: 5000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'taxonomies',
    chapter: 'organizer',
    title: 'Tracks, rooms, and formats',
    body: 'Define programme vocabulary once. The CFP, review workspace, agenda, and public schedule reuse these populated lists.',
    route: '/admin/events/$slug/taxonomies',
    params: eventParams,
    access: 'organizer',
    target: 'taxonomy-workspace',
    mobileTarget: 'taxonomy-workspace',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['Three tracks', 'Two rooms', 'Three formats'],
    maxTransitionMs: 5000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'cfp-builder',
    chapter: 'organizer',
    title: 'Build and version the CFP',
    body: 'The demonstration draft shows pages, validation, a Workshop condition, track routing, preview, and the immutable published version.',
    route: '/admin/events/$slug/forms/$formId',
    params: { slug: DEFAULT_EVENT_SLUG, formId: showcaseFormId },
    access: 'organizer',
    target: 'cfp-builder-workspace',
    mobileTarget: 'cfp-builder-workspace',
    targetPolicy: 'required',
    mode: 'guided',
    placement: 'auto',
    fixtureAssertions: ['Tour-safe draft', 'Workshop condition', 'Published version'],
    maxTransitionMs: 7000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'submissions',
    chapter: 'organizer',
    title: 'Proposal intake',
    body: 'Twelve seeded proposals show accepted, rejected, and pending states. Try the filters without changing programme data.',
    route: '/admin/events/$slug/submissions',
    params: eventParams,
    access: 'organizer',
    target: 'submissions-table',
    mobileTarget: 'submissions-table',
    targetPolicy: 'required',
    mode: 'guided',
    placement: 'auto',
    fixtureAssertions: ['Twelve proposals', 'Mixed decisions'],
    maxTransitionMs: 6000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'submission-workspace',
    chapter: 'organizer',
    title: 'One proposal, fully connected',
    body: 'The featured proposal keeps frozen answers, speakers, committee evidence, its decision, onboarding, and schedule placement together.',
    route: '/admin/events/$slug/submissions/$submissionId',
    params: { slug: DEFAULT_EVENT_SLUG, submissionId: showcaseSubmissionId },
    access: 'organizer',
    target: 'submission-workspace',
    mobileTarget: 'submission-workspace',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['Featured proposal', 'Accepted decision', 'Evaluation evidence'],
    maxTransitionMs: 6000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'speakers',
    chapter: 'organizer',
    title: 'Speaker desk',
    body: 'Profiles, portal access, onboarding progress, and communication actions stay attached to the accepted programme.',
    route: '/admin/events/$slug/speakers',
    params: eventParams,
    access: 'organizer',
    target: 'speakers-roster',
    mobileTarget: 'speakers-roster',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['Populated speaker roster'],
    maxTransitionMs: 6000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'messages',
    chapter: 'organizer',
    title: 'Delivery history',
    body: 'This audit shows immutable delivery history and provider outcomes. Message composition and reminders begin from the speaker desk.',
    route: '/admin/events/$slug/messages',
    params: eventParams,
    access: 'organizer',
    target: 'messages-workspace',
    mobileTarget: 'messages-workspace',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['Captured and delivered message outcomes'],
    maxTransitionMs: 5000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'evaluations',
    chapter: 'organizer',
    title: 'Review rounds and results',
    body: 'Criteria, assignments, weighted results, and recusal evidence give organizers a complete human-review picture.',
    route: '/admin/events/$slug/evaluations',
    params: eventParams,
    access: 'organizer',
    target: 'evaluations-workspace',
    mobileTarget: 'evaluations-workspace',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['Two review rounds', 'Weighted results', 'Recusal'],
    maxTransitionMs: 6000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'agenda',
    chapter: 'organizer',
    title: 'Build the agenda',
    body: 'Eight placed sessions, one invited keynote waiting for a slot, explicit conflicts, and every projection read from one canonical schedule.',
    route: '/admin/events/$slug/agenda',
    params: eventParams,
    access: 'organizer',
    target: 'agenda-board',
    mobileTarget: 'agenda-board',
    targetPolicy: 'required',
    mode: 'guided',
    placement: 'auto',
    fixtureAssertions: ['Nine agenda sessions', 'Invited keynote', 'Known conflict'],
    maxTransitionMs: 7000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'embeds',
    chapter: 'organizer',
    title: 'Publish an embed',
    body: 'A saved schedule embed provides canonical copyable code and a live preview tied to the same programme.',
    route: '/admin/events/$slug/embeds',
    params: eventParams,
    access: 'organizer',
    target: 'embeds-workspace',
    mobileTarget: 'embeds-workspace',
    targetPolicy: 'required',
    mode: 'guided',
    placement: 'auto',
    fixtureAssertions: ['Saved schedule embed', 'Live preview'],
    maxTransitionMs: 6000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'files',
    chapter: 'organizer',
    title: 'Files and speaker resources',
    body: 'Uploads stay owner-linked and versioned, while safe Markdown guides and event links publish to every speaker portal.',
    route: '/admin/events/$slug/files',
    params: eventParams,
    access: 'organizer',
    target: 'files-workspace',
    mobileTarget: 'files-workspace',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['Headshot metadata', 'Presentation metadata', 'Three speaker resources'],
    maxTransitionMs: 6000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'orby',
    chapter: 'organizer',
    title: 'Event support desk',
    body: 'Orby is the event support inbox. A synthetic conversation shows how attendee questions and organizer replies stay inside DemoConf.',
    route: '/admin/events/$slug/orby',
    params: eventParams,
    access: 'organizer',
    target: 'orby-workspace',
    mobileTarget: 'orby-workspace',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['Synthetic support conversation'],
    maxTransitionMs: 5000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'readiness',
    chapter: 'organizer',
    title: 'Know what is missing',
    body: 'The readiness pulse shows task completion, sessions ready, and the most common blocker, then links to the people behind each number.',
    route: '/admin/events/$slug/readiness',
    params: eventParams,
    access: 'organizer',
    target: 'readiness-overview',
    mobileTarget: 'readiness-overview',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['30 percent task completion', 'Five of eight sessions ready'],
    maxTransitionMs: 5000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'palette',
    chapter: 'organizer',
    title: 'Shortcuts menu',
    body: 'Open the shortcuts menu to reach any allowed organizer destination. On desktop, the same tool is the Command menu and opens with the keyboard shortcut.',
    access: 'organizer',
    target: 'palette-trigger',
    mobileTarget: null,
    targetPolicy: 'optional',
    mode: 'guided',
    placement: 'auto',
    fixtureAssertions: ['Allowed organizer destinations'],
    maxTransitionMs: 3000,
    requiresSession: 'organizer',
  }),
  moment({
    id: 'public-cfp',
    chapter: 'submitter',
    title: 'The published call for papers',
    body: 'The public stepper renders the organizer’s published form, including the Workshop condition and category routing.',
    route: '/cfp/$eventSlug/$formSlug',
    params: { eventSlug: DEFAULT_EVENT_SLUG, formSlug: DEFAULT_FORM_SLUG },
    access: 'public',
    target: 'cfp-stepper',
    mobileTarget: 'cfp-stepper',
    targetPolicy: 'required',
    mode: 'guided',
    placement: 'auto',
    fixtureAssertions: ['Four-step CFP', 'Workshop conditional field'],
    maxTransitionMs: 7000,
  }),
  moment({
    id: 'start',
    chapter: 'submitter',
    title: 'Role-specific access',
    body: 'Speakers request a CFP link here. Portal and reviewer links are organizer-issued, and organizer sign-in remains separate.',
    route: '/start',
    access: 'public',
    target: 'start-page',
    mobileTarget: 'start-page',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['Speaker access form', 'Organizer access guidance'],
    maxTransitionMs: 5000,
  }),
  moment({
    id: 'speaker-portal',
    chapter: 'speaker',
    title: 'Speaker readiness and resources',
    body: 'Accepted and invited sessions share the same tasks, resource guides, profile, files, and calendar handoff.',
    route: '/portal',
    access: 'portal',
    target: 'speaker-portal',
    mobileTarget: 'speaker-portal',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: [
      'Accepted featured session',
      'Invited keynote',
      'Mixed task state',
      'Resources',
    ],
    maxTransitionMs: 7000,
  }),
  moment({
    id: 'speaker-files',
    chapter: 'speaker',
    title: 'Profile and presentation files',
    body: 'The speaker can inspect profile, headshot, file request, deck, and version history without leaving the portal.',
    route: '/portal',
    access: 'portal',
    target: 'portal-files',
    mobileTarget: 'portal-files',
    targetPolicy: 'required',
    mode: 'guided',
    placement: 'auto',
    fixtureAssertions: ['Profile', 'Headshot', 'Deck metadata', 'File request'],
    maxTransitionMs: 5000,
  }),
  moment({
    id: 'reviewer-queue',
    chapter: 'reviewer',
    title: 'Reviewer queue',
    body: 'The reviewer sees only assigned proposals, each criterion, saved score state, and the recusal action for conflicts.',
    route: '/evaluations',
    access: 'evaluation',
    target: 'reviewer-assignment',
    mobileTarget: 'reviewer-assignment',
    targetPolicy: 'required',
    mode: 'guided',
    placement: 'auto',
    fixtureAssertions: ['Assigned proposal', 'Saved score', 'Recusal action'],
    maxTransitionMs: 7000,
  }),
  moment({
    id: 'session-catalogue',
    chapter: 'programme',
    title: 'Browse published sessions',
    body: 'Search and filter eight public sessions, then open the details that matter. Reviewer authority is already closed.',
    route: '/sessions/$eventSlug',
    params: { eventSlug: DEFAULT_EVENT_SLUG },
    access: 'public',
    target: 'session-catalogue',
    mobileTarget: 'session-catalogue',
    targetPolicy: 'required',
    mode: 'guided',
    placement: 'auto',
    fixtureAssertions: ['Eight published sessions', 'Search and filters'],
    maxTransitionMs: 6000,
  }),
  moment({
    id: 'speaker-gallery',
    chapter: 'programme',
    title: 'Meet the speakers',
    body: 'The public gallery connects each presenter to a profile and their published sessions without exposing private contact data.',
    route: '/speakers/$eventSlug',
    params: { eventSlug: DEFAULT_EVENT_SLUG },
    access: 'public',
    target: 'speaker-gallery',
    mobileTarget: 'speaker-gallery',
    targetPolicy: 'required',
    mode: 'observe',
    placement: 'auto',
    fixtureAssertions: ['Eight public speakers', 'Session relationships'],
    maxTransitionMs: 6000,
  }),
  moment({
    id: 'schedule',
    chapter: 'programme',
    title: 'The published schedule',
    body: 'The organizer’s agenda becomes an attendee schedule with list, day, week, track, and room views and working session details.',
    route: '/schedule/$eventSlug',
    params: { eventSlug: DEFAULT_EVENT_SLUG },
    access: 'public',
    target: 'schedule-grid',
    mobileTarget: 'schedule-grid',
    targetPolicy: 'required',
    mode: 'guided',
    placement: 'auto',
    fixtureAssertions: ['Eight sessions across two days', 'Five projections'],
    maxTransitionMs: 6000,
  }),
  moment({
    id: 'itinerary',
    chapter: 'programme',
    title: 'Save and export an itinerary',
    body: 'Star sessions, keep the itinerary on this device, open one session in Google or Outlook, or export standards-based iCalendar files.',
    route: '/schedule/$eventSlug',
    params: { eventSlug: DEFAULT_EVENT_SLUG },
    access: 'public',
    target: 'itinerary-action',
    mobileTarget: 'itinerary-action',
    targetPolicy: 'required',
    mode: 'guided',
    placement: 'auto',
    fixtureAssertions: ['Itinerary controls', 'Google and Outlook actions', 'iCalendar export'],
    maxTransitionMs: 5000,
  }),
]

export const TOUR_SIGN_IN_STEP_INDEX = TOUR_STEPS.findIndex((step) => step.id === 'admin-signin')

export function publicResumeIndexAfter(index: number): number {
  return TOUR_STEPS.findIndex(
    (step, at) => at > index && step.access === 'public' && step.route !== undefined,
  )
}

export function tourChapterForStep(stepId: string): TourChapterId | null {
  return TOUR_STEPS.find((step) => step.id === stepId)?.chapter ?? null
}
